### ISSUE TITLE
"target":"_blank" is not working

### ISSUE THREAD

**Issue by Sumeetgrg** [ali-saleem/anchorme.js#28]
I am using anchrome.js and trying to open link in a new tab.
While trying using attribute feature, it's not working:

anchorme("screencast.com", {
                    attribute: {
                        "target": "_blank"
                    }
                })
above code producing following: "<a href='http://screencast.com'>http://screencast.com</a>"
 
For reference:
http://screencast.com/t/206XmVpSd9LN

**Comment by alexcorvi** [comment]
There was a typo in the readme.md example, it's fixed now in #27 

Please try this:

```javascript
anchorme("screencast.com", {
    attribute: {
        "target": "_blank"
    }
})
```

Also, I've added the options to the test suite, and confirmed that everything is working properly.

Thank you for bringing this to my attention!

**Comment by Sumeetgrg** [comment]
Thanks Alex your awesome

**Comment by fknorn** [comment]
Sorry, still not working for my with latest version 161a2af. If I run your "Please try this" blob, I still don't get a link with target _blank...

**Comment by alexcorvi** [comment]
@fknorn There was a small API change in the last version

Try this:

```javascript
    anchorme("github.com",{
        attributes:[
            {
                // attribute name
                name:"target",
                // attribute value
                value:"_blank"
            }
        ]
    });
```

This change was necessary to add conditional attributes to a link, read the current [readme.md](https://github.com/alexcorvi/anchorme.js/blob/gh-pages/README.md#adding-attributes) for more.

**Comment by fknorn** [comment]
Hi Alex,

thanks for getting back to me, but nope, still not working on my end :( I get a link, yes, but no target _blank. That is, using above build of anchorme, trying both lastest jQuery 1.x and 2.x, and the following code:
```javascript
var $html = $(e).html();
$html = anchorme($html,{
	attributes:[{
		// attribute name
		name:"target",
		// attribute value
		value:"_blank"
	}],
	truncate:20
});
$(e).html($html);
```
... or am I just doing something completely wrong?

Thanks again for your time and efforts!!

**Comment by alexcorvi** [comment]
@fknorn Alright, it seems like the `.min` version was an outdated build for some reason!
It's fixed now. You can try [this fiddle](https://jsfiddle.net/7ugpefv6/).

**Comment by fknorn** [comment]
Confirmed, thank you very much. Well spotted, too :-) 👍
