### ISSUE TITLE
es6 import with Typescript

### ISSUE THREAD

**Issue by markcellus** [ali-saleem/anchorme.js#63]
Trying to import this package with TypeScript using following es6 import but is not working.

```js
import anchorme from 'anchorme';
``` 

which gives me the following error:

```
Error: 'default' is not exported by node_modules/anchorme/dist-node/index.js
```

What is the preferred way to import this package?

**Comment by cyberjj999** [comment]
Im having the same issue as well , have u found the solution yet?

**Comment by alexcorvi** [comment]
Fixed in __2.0.0__
- [Release note](https://github.com/alexcorvi/anchorme.js/releases/tag/2.0.0)
- [Documentation, JSFiddles, and demos](http://alexcorvi.github.io/anchorme.js/)

**Comment by markcellus** [comment]
@alexcorvi sorry for taking so long to get around to checking this but it still doesn't work. I pulled in latest version 2.1.2 and still gives me the same error. Can we reopen issue? Thanks!

**Comment by markcellus** [comment]
@alexcorvi any word on reopening issue? I'd really like to continue using anchorme.js but this blocks me from using it on a typescript project.
